name: CI

on:
  push:
  pull_request:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install deps
        run: bun install

      - name: Lint & Format
        run: bunx biome ci .

      - name: Generate Prisma
        run: bun run prisma:generate
        working-directory: apps/api

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build
